// Generated by CoffeeScript 1.9.3
(function() {
  var add, changeNumbers, countdown, date, fill, fill2, grade, method, num, nums, outer, singers, singers2, temp;

  alert("hello coffeescript");

  num = 5;

  add = function(a, b) {
    return a + b;
  };

  method = {
    root: root,
    square: square,
    cube: function(x) {
      return x + 1;
    }
  };

  fill = function(container, liquid) {
    if (liquid == null) {
      liquid = "coffee";
    }
    return "Filling the " + container + " with " + liquid + "...";
  };

  fill2 = function(container, liquid) {
    return "Filling the " + container + " with " + liquid + "...";
  };

  singers = {
    jagger: "Rock",
    Elvis: "Roll"
  };

  singers2 = {
    Jagger: "Rock",
    Elvis: "Roll"
  };

  $('div').attr({
    "class": 'active'
  });

  outer = 1;

  changeNumbers = function() {
    var inner;
    inner = -1;
    return outer = 10;
  };

  date = friday ? sue : jill;

  if (abc && def) {
    showDiff();
  } else {
    showSame();
  }

  if (abc && def) {
    temp = ok;
  }

  nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  countdown = (function() {
    var i, results;
    results = [];
    for (num = i = 10; i <= 1; num = i += 2) {
      results.push(num);
    }
    return results;
  })();

  grade = function(student) {
    if (student.excellentWord) {
      return "A";
    } else if (student.okayStuff) {
      if (student.tryHard) {
        return "B";
      } else {
        return "B-";
      }
    } else {
      return "c";
    }
  };

  this.property = 3;

}).call(this);
